services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  web-ui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: web-ui
    depends_on:
      - ollama
    restart: always
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - "8081:8080"
    volumes:
      - open-webui:/app/backend/data
    networks:
      - ollama-docker
volumes:
  ollama: {}
  open-webui: {}
networks:
  ollama-docker: { }